# Generated by Django 2.1.15 on 2020-01-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkskyApi',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_darksky_api_darkskyapi', serialize=False, to='cms.CMSPlugin')),
                ('latitude', models.DecimalField(db_index=True, decimal_places=25, help_text='e.g.: 44.988208', max_digits=27, verbose_name='Latitude')),
                ('longitude', models.DecimalField(db_index=True, decimal_places=24, help_text='e.g.: 4.976723', max_digits=27, verbose_name='Longitude')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
