# Generated by Django 2.2.9 on 2020-01-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_darksky_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkskyapi',
            name='template',
            field=models.CharField(choices=[('SM', 'Small'), ('ME', 'Medium')], default='SM', max_length=2),
        ),
    ]
