# Generated by Django 2.2.9 on 2020-01-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_darksky_api', '0002_darkskyapi_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='darkskyapi',
            old_name='template',
            new_name='template_size',
        ),
    ]
